// Vetted GIBS layer catalog.
// Sourced from NASA GIBS WMTS docs + Worldview's curated config.
// Each entry includes the actual matrixSet/maxLevel/format and per-layer latency
// so the runtime can pick a date that GIBS actually has tiles for.

import type { GIBSLayerConfig } from '../layers/GIBSLayerManager';

export const GIBS_LAYERS: GIBSLayerConfig[] = [
  // ========== TRUE COLOR BASEMAPS ==========
  {
    id: 'modis-terra-truecolor',
    name: 'MODIS Terra True Color',
    category: 'Basemap',
    layer: 'MODIS_Terra_CorrectedReflectance_TrueColor',
    tileMatrixSetID: '250m',
    format: 'image/jpeg',
    maxLevel: 8,
    period: 'daily',
    lagDays: 2,
    isDefault: true,
  },
  {
    id: 'modis-aqua-truecolor',
    name: 'MODIS Aqua True Color',
    category: 'Basemap',
    layer: 'MODIS_Aqua_CorrectedReflectance_TrueColor',
    tileMatrixSetID: '250m',
    format: 'image/jpeg',
    maxLevel: 8,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'viirs-snpp-truecolor',
    name: 'VIIRS SNPP True Color',
    category: 'Basemap',
    layer: 'VIIRS_SNPP_CorrectedReflectance_TrueColor',
    tileMatrixSetID: '250m',
    format: 'image/jpeg',
    maxLevel: 8,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'viirs-noaa20-truecolor',
    name: 'VIIRS NOAA-20 True Color',
    category: 'Basemap',
    layer: 'VIIRS_NOAA20_CorrectedReflectance_TrueColor',
    tileMatrixSetID: '250m',
    format: 'image/jpeg',
    maxLevel: 8,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'bluemarble',
    name: 'Blue Marble (Static)',
    category: 'Basemap',
    layer: 'BlueMarble_NextGeneration',
    tileMatrixSetID: '500m',
    format: 'image/jpeg',
    maxLevel: 8,
    period: 'static',
    lagDays: 0,
  },

  // ========== NIGHT / LIGHTS ==========
  {
    id: 'viirs-nightlights',
    name: 'VIIRS Night Lights (ENCC)',
    category: 'Night',
    layer: 'VIIRS_SNPP_DayNightBand_ENCC',
    tileMatrixSetID: '500m',
    format: 'image/png',
    maxLevel: 7,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'viirs-nightlights-2024',
    name: 'VIIRS Black Marble 2024',
    category: 'Night',
    layer: 'VIIRS_Black_Marble',
    tileMatrixSetID: '500m',
    format: 'image/png',
    maxLevel: 7,
    period: 'static',
    lagDays: 0,
  },

  // ========== FIRE / THERMAL ==========
  {
    id: 'firms-modis-thermal',
    name: 'MODIS Thermal Anomalies (Combined)',
    category: 'Fire',
    layer: 'MODIS_Combined_Thermal_Anomalies_All',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: 'daily',
    lagDays: 1,
  },
  {
    id: 'firms-viirs-snpp-thermal',
    name: 'VIIRS SNPP Thermal Anomalies',
    category: 'Fire',
    layer: 'VIIRS_SNPP_Thermal_Anomalies_375m_All',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: 'daily',
    lagDays: 1,
  },
  {
    id: 'firms-viirs-noaa20-thermal',
    name: 'VIIRS NOAA-20 Thermal Anomalies',
    category: 'Fire',
    layer: 'VIIRS_NOAA20_Thermal_Anomalies_375m_All',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: 'daily',
    lagDays: 1,
  },

  // ========== AIR QUALITY / AEROSOL ==========
  {
    id: 'aerosol-modis-aqua',
    name: 'MODIS Aqua Aerosol Optical Depth',
    category: 'Air',
    layer: 'MODIS_Aqua_Aerosol',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'aerosol-modis-terra',
    name: 'MODIS Terra Aerosol Optical Depth',
    category: 'Air',
    layer: 'MODIS_Terra_Aerosol',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 2,
  },

  // ========== OCEAN ==========
  {
    id: 'sst-mur',
    name: 'Sea Surface Temperature (MUR)',
    category: 'Ocean',
    layer: 'GHRSST_L4_MUR_Sea_Surface_Temperature',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: 'daily',
    lagDays: 2,
  },
  {
    id: 'chlorophyll-pace',
    name: 'PACE Chlorophyll a',
    category: 'Ocean',
    layer: 'PACE_OCI_L3M_CHL',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 3,
  },

  // ========== WEATHER / PRECIP ==========
  {
    id: 'imerg-precip',
    name: 'IMERG Precipitation Rate',
    category: 'Weather',
    layer: 'IMERG_Precipitation_Rate',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'half-hourly',
    lagDays: 0,
  },
  {
    id: 'amsr2-cloud-water',
    name: 'AMSR2 Cloud Liquid Water',
    category: 'Weather',
    layer: 'AMSR2_Cloud_Liquid_Water_Day',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 1,
  },

  // ========== ICE / SNOW ==========
  {
    id: 'sea-ice-conc',
    name: 'AMSR2 Sea Ice Concentration',
    category: 'Cryosphere',
    layer: 'AMSR2_Sea_Ice_Concentration_12km',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 1,
  },
  {
    id: 'snow-cover',
    name: 'MODIS Snow Cover',
    category: 'Cryosphere',
    layer: 'MODIS_Terra_NDSI_Snow_Cover',
    tileMatrixSetID: '500m',
    format: 'image/png',
    maxLevel: 7,
    period: 'daily',
    lagDays: 1,
  },

  // ========== LAND / VEGETATION ==========
  {
    id: 'land-surface-temp-day',
    name: 'MODIS Land Surface Temp (Day)',
    category: 'Land',
    layer: 'MODIS_Terra_Land_Surface_Temp_Day',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: 'daily',
    lagDays: 1,
  },
  {
    id: 'ndvi',
    name: 'MODIS NDVI (Vegetation Index)',
    category: 'Land',
    layer: 'MODIS_Terra_NDVI_8Day',
    tileMatrixSetID: '1km',
    format: 'image/png',
    maxLevel: 6,
    period: '8-day',
    lagDays: 8,
  },

  // ========== REFERENCE / ORBITS ==========
  {
    id: 'orbits-snpp',
    name: 'Orbit Tracks – SNPP (Asc)',
    category: 'Reference',
    layer: 'OrbitTracks_Suomi_NPP_Ascending',
    tileMatrixSetID: '2km',
    format: 'image/png',
    maxLevel: 5,
    period: 'daily',
    lagDays: 0,
  },
  {
    id: 'reference-coastlines',
    name: 'Coastlines / Borders',
    category: 'Reference',
    layer: 'Coastlines_15m',
    tileMatrixSetID: '15.625m',
    format: 'image/png',
    maxLevel: 9,
    period: 'static',
    lagDays: 0,
  },
];

export const GIBS_DEFAULT_LAYER_ID = GIBS_LAYERS.find(l => l.isDefault)?.id ?? GIBS_LAYERS[0].id;

export const GIBS_CATEGORIES = Array.from(new Set(GIBS_LAYERS.map(l => l.category)));
